### ISSUE TITLE
GH Secrets file formats

### ISSUE THREAD

**Issue by mrecos** [revodavid/mlops-r-gha#1]
Hello David, Thanks for this great repo. Could you clarify this bullet point from `Setup-DSVM.md`?

Add the SHINYKEY secret to your forked repo in GitHub with the private SSH key needed to access shinyserver. Also add SHINYHOST with the SHINYSERVERIP address, set SHINYUSERNAME to azureuser, and SHINYPORT to 3838.

I assume this is the same format as the `AZURE_CREDENTIALS` secret, but I cannot see what all the key pair names should be.
Thank you!

**Comment by revodavid** [comment]
Thanks for the feedback Matt, I’ll make the instructions clearer. They’re not JSON key-value pairs, just single text strings as separate GitHub secrets.

For SHINYKEY, paste in the entire contents of your SSH private key file.

(corrected) For SHINYHOST, paste in the IP address of the shinyserver VM (in the format AAA.AAA.AAA.AAA).

For SHINYUSERNAME and SHINYPORT just make secrets with the values listed.

**Comment by mrecos** [comment]
Thank you Dave. Quick question, the line "For SHINYSERVERIP, paste in ..." should be "For SHINYHOST, paste in ..." by the looks of your original instructions?

**Comment by revodavid** [comment]
Ah yes, that's correct, SHINYHOST is the secret -- thanks.

**Comment by mrecos** [comment]
Thanks Dave! please see Pull Request #2 for suggested updates based on this issue.
